services: postgresql
before_script: psql -c 'create database passport_local_knex_test;' -U postgres
language: node_js
node_js: node
after_success: npm run coverage
script: yarn test && yarn prod:build
